# Generated by Django 5.2.6 on 2025-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('adress', models.CharField(blank=True, default='', max_length=255)),
                ('forecast', models.CharField(blank=True, default='', max_length=100)),
                ('cold_water_supply', models.FloatField(default=0.0)),
                ('cold_water_diff', models.FloatField(default=0.0)),
                ('reverse_water', models.FloatField(default=0.0)),
                ('reverse_water_diff', models.FloatField(default=0.0)),
                ('t1', models.FloatField(default=0.0)),
                ('t2', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Норма'), ('warning', 'Отклонение'), ('danger', 'Авария')], default='')),
            ],
        ),
    ]
