# Generated by Django 5.2.6 on 2025-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testalerts',
            name='house_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
