# Generated by Django 5.2.6 on 2025-09-23 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_testalerts_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testalerts',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
