# Generated by Django 5.2.6 on 2025-09-25 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_testalerts_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='')),
                ('adress', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('critical', 'Критическое')], default='')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Низкий приоритет'), ('medium', 'Средний приоритет'), ('high', 'Высокий приоритет')], default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='TestAlerts',
            new_name='HouseAlerts',
        ),
    ]
