# Generated by Django 5.2.6 on 2025-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alerts_rename_testalerts_housealerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='alert_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='housealerts',
            name='house_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
