# Generated by Django 5.2.6 on 2025-09-26 17:27

import dashboards.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alerts_alert_id_alter_housealerts_house_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SavedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(max_length=255, upload_to=dashboards.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='DetectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField(default=0.0)),
                ('detector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.detector')),
            ],
        ),
        migrations.CreateModel(
            name='DetectorTreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
                ('detector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.detector')),
            ],
        ),
        migrations.AddField(
            model_name='detector',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.detectortypes'),
        ),
        migrations.CreateModel(
            name='DetectorsAtHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_id', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.house')),
            ],
        ),
        migrations.CreateModel(
            name='ModelForHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.house')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.savedmodel')),
            ],
        ),
    ]
