# Generated by Django 5.2.6 on 2025-09-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_detector_detectortypes_house_savedmodel_detectordata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorsathouse',
            name='detector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.detector'),
        ),
    ]
