# Generated by Django 5.2.6 on 2025-09-27 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_detectorsathouse_detector_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, choices=[('normal', 'Норма'), ('sensor_failure', 'Сбой датчика')], default='')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.house')),
            ],
        ),
    ]
