# Generated by Django 5.2.6 on 2025-10-01 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0008_statelabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelforhouse",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
