# Generated by Django 5.2.6 on 2025-10-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0009_modelforhouse_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmodel",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
    ]
