# Generated by Django 5.2.6 on 2025-10-02 10:33

import dashboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_savedmodel_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedmodel',
            old_name='file',
            new_name='metadata_file',
        ),
        migrations.AddField(
            model_name='savedmodel',
            name='model_file',
            field=models.FileField(default='', max_length=255, upload_to=dashboards.models.user_directory_path),
            preserve_default=False,
        ),
    ]
