# Generated by Django 5.2.6 on 2025-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_rename_file_savedmodel_metadata_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelabel',
            name='state',
            field=models.CharField(blank=True, choices=[('normal', 'Норма'), ('sensor_failure', 'Сбой датчика'), ('gradual_leak', 'Постепенная утечка'), ('sharp_leak', 'Утечка'), ('unknown', '')], default='unknown'),
        ),
    ]
