# Generated by Django 5.2.6 on 2025-10-02 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_statelabel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='statelabel',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statelabel',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast', models.CharField(blank=True, default='', max_length=1000)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.house')),
            ],
        ),
    ]
