# Generated by Django 5.2.6 on 2025-10-18 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_statelabel_confidence_statelabel_confirmed_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('xvs', models.SmallIntegerField(default=0)),
                ('gvs', models.SmallIntegerField(default=0)),
                ('cold_water_supply', models.SmallIntegerField(default=0)),
                ('reverse_flow', models.SmallIntegerField(default=0)),
                ('t1', models.SmallIntegerField(default=0)),
                ('t2', models.SmallIntegerField(default=0)),
                ('sensivity', models.FloatField(default=0.0)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.house')),
            ],
        ),
    ]
